### PR TITLE
Maven integration

### PR DESCRIPTION
**Pull request by kichik**
Added a maven plugin that automatically validates all .sdl files in a given folder. It's very raw, but gets the job done.  This is for issue #4.

### CODE REVIEW

**Comment by philipl** [comment]
Hi - this is a great idea. Could I ask you to update your files with the right licence header? Otherwise we won't be able to do anything with it.

Thanks!

**Comment by kichik** [comment]
Thanks. I pushed a license header to the same branch. Let me know if there is anything else I can do to get this merged and show up on a public maven repo.

**Comment by philipl** [comment]
Due to how we stage our releases, it will be a while before we can publish the actual plugin, but we will publish the validator jar very soon. Thanks.

**Comment by philipl** [comment]
There were some changes in 5.4.0 that introduce complications into this plugin. I've made a fix that will be in 5.4.1. I'll be trying to include the plugin at that point.

**Comment by philipl** [comment]
Maven plugin is now published. Thanks!

**Comment by kichik** [comment]
Thanks! Here's what works for me now. Not sure why I have to manually
define the dependency versions, but it won't find them without it.

```xml
<build>
  <plugins>
    <plugin>
      <groupId>com.cloudera.enterprise</groupId>
      <artifactId>schema-validator-maven-plugin</artifactId>
      <version>5.4.3</version>
      <executions>
        <execution>
          <phase>test</phase>
          <goals>
            <goal>validate</goal>
          </goals>
          <configuration>
            <sourceDirectory>src</sourceDirectory>
          </configuration>
        </execution>
      </executions>
      <dependencies>
        <dependency>
          <groupId>com.cloudera.cmf.schema</groupId>
          <artifactId>cloudera-manager-schema</artifactId>
          <version>5.4.0</version>
        </dependency>
        <dependency>
          <groupId>com.cloudera.enterprise</groupId>
          <artifactId>schema-validator</artifactId>
          <version>5.4.2</version>
        </dependency>
      </dependencies>
    </plugin>
  </plugins>
</build>
```
On Jun 9, 2015 13:51, "Philip Langdale" <notifications@github.com> wrote:

Maven plugin is now published. Thanks!

—
Reply to this email directly or view it on GitHub
<https://github.com/cloudera/cm_ext/pull/5#issuecomment-110500691>.

**Comment by philipl** [comment]
I thought that was normal.

**Comment by kichik** [comment]
I don't believe it is. Other plugins find the right dependency version
automatically. I think it's because the validator plugin is 5.4.3 but the
schema and validator are not. Maybe the plugin POM needs to define a
version specifically.

**Pull request closed without merging**
